[package]
name = "universal_mask"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "A library for formatting sensitive data with masks like SSN and phone numbers"

[dependencies]
